<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MPEGTSStreamer</RootNamespace>
    <AssemblyName>MPEGTSStreamer</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LoggerService">
      <HintPath>lib\LoggerService.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="lib\LoggerService.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MPEGTS\MPEGTS.csproj" />
  </ItemGroup>

</Project>