<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MPEGTSAnalyzator</RootNamespace>
    <AssemblyName>MPEGTSAnalyzator</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MPEGTransportStreamPacket.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LoggerService">
      <HintPath>lib\LoggerService.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="lib\LoggerService.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MPEGTS\MPEGTS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData.Crete\**\*.ts">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData.China\**\*.ts">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData.CZ\**\*.ts">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData.IT\DVBT-MPEGTS-610MHz-2023-08-16-15-53-49.ts">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestData.Germany\**\*.ts">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TestData.IT\DVBT-MPEGTS-650MHz-2024-03-12-16-50-02.ts">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TestData.PL\**\*.ts">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>