<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>.NET MPEG Transport Stream library</Title>
    <RepositoryUrl>https://github.com/petrj/NugetLibrary</RepositoryUrl>
    <Description>.NET MPEG Transport Stream library</Description>
    <PackageProjectUrl>https://github.com/petrj/MPEGTS</PackageProjectUrl>
    <AssemblyVersion>1.0.0.27</AssemblyVersion>
    <FileVersion>1.0.0.27</FileVersion>
    <PackageVersion>1.0.27</PackageVersion>
    <Authors>Petr Janousek</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="lib\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="NLog" Version="5.3.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="LoggerService">
      <HintPath>lib\LoggerService.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
